---
- name: Graylog
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  hosts: localhost
  vars:
    service_name: "{{ SERVICE }}"
  roles:
    - java
    - graylog
    - nginx